version: "3.3"

services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d
            # - ./nginx/logs:/var/log/nginx
       
        links:
            - php-fpm
    php-fpm:
        restart: always
        image: marcosseixas/workstation-php-8-1-fpm 
        volumes:
            - ../:/var/www

    redis:
        network_mode: host
        image: redis
        command: redis-server
        restart: always

    server-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'database_name'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
         - '3306:3306'
        # - '3307:3306'
        volumes:
            - ./mysql/db:/var/lib/mysql