version: "3.3"

services:
    web:
        image: nginx:latest
        ports:
            # - "8080:80"
            - "80:80"
        volumes:
            - ../:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        links:
            - php-fpm

    php-fpm:
        image: marcosseixas/workstation-php-8-1
        volumes:
            - ../:/var/www/html

    server-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'database_name'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
         - '3306:3306'
        # - '3307:3306'
        volumes:
            - ./mysql/db:/var/lib/mysql
volumes: 
    server-mysql: